In [14]:
# install openCV package
!pip3 install opencv-python-headless

# To get the average frame count
import glob
import numpy as np
import cv2
import os

# Update the path to your desired directory
video_directory = 'F:/Master/Research Project/Datasets/DFDC/Experiment Dataset/dfdc_train_part_1_exp'

# To get the average frame count 
video_files =  glob.glob(video_directory + '/*.mp4')

# new code
video_files = [os.path.normpath(file) for file in video_files]


frame_count = []
for video_file in video_files:
  cap = cv2.VideoCapture(video_file)
  if(int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) < 150):
    video_files.remove(video_file)
    continue
  frame_count.append(int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))

print("frames", frame_count)
print("Total number of videos:", len(frame_count))
print('Average frame per video:', np.mean(frame_count))

frames [299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 300, 299, 300, 299, 299, 299, 299, 300, 300, 299, 299, 299, 299, 299, 299, 300, 299, 300, 299, 300, 299, 299, 299, 299, 300, 299, 299, 299, 299, 300, 300, 299, 299, 299, 299, 300, 299, 299, 299, 299, 299, 300, 299, 299, 299, 300, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 300, 299, 300, 299, 299, 300, 299, 300, 300, 299, 299, 299, 299, 299, 299, 299, 299, 299, 300, 300, 300, 299, 300, 299, 299, 299, 299, 300, 299, 299, 299, 299, 300, 299, 299, 299, 299, 299, 299, 300, 299, 299, 299, 300, 299, 299, 300, 299, 300, 299, 299, 299, 299, 299, 299, 300, 299, 299, 299, 299, 300, 299, 299, 299, 299, 300, 299, 300, 299, 300, 299, 299, 299, 299, 299, 300, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 300, 299, 299, 299, 299, 299, 300, 300, 299, 299, 299, 299, 299, 299, 299, 299, 299, 299, 300, 299, 299, 299, 300, 299, 299, 299, 299, 299, 299, 300, 299, 299, 300, 299, 299, 299, 29

In [11]:
!pip3 install face_recognition
!pip3 install torch
!pip3 install torchvision
# !mkdir 'F:/Master/Research Project/Generated Data/DFDC_Face_only_data'

^C


In [6]:
!pip3 install mtcnn
!pip3 install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/1c/c3/17c6aa1dd5bc8cea5bf00d0c3a021a5dd1680c250861cc877a7e556e4b9b/tensorflow-2.14.0-cp310-cp310-win_amd64.whl.metadata
  Using cached tensorflow-2.14.0-cp310-cp310-win_amd64.whl.metadata (3.3 kB)
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/cb/90/599c79a248dcae6935331113649de5d75427e320efde21b583648b498584/tensorflow_intel-2.14.0-cp310-cp310-win_amd64.whl.metadata
  Using cached tensorflow_intel-2.14.0-cp310-cp310-win_amd64.whl.metadata (4.8 kB)
Using cached tensorflow-2.14.0-cp310-cp310-win_amd64.whl (2.1 kB)
Using cached tensorflow_intel-2.14.0-cp310-cp310-win_amd64.whl (284.1 MB)


In [7]:
from mtcnn import MTCNN

In [9]:
# to extract frame into images
def frame_extract(path):
    vidObj = cv2.VideoCapture(path)
    success = 1
    while success:
        success, image = vidObj.read()
        if success:
            yield image

In [11]:
!pip3 install tqdm

  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)


In [50]:
from tqdm.autonotebook import tqdm
from mtcnn import MTCNN

# Load MTCNN detector
detector = MTCNN()


# Refactored function to create face images
def create_face_images(path_list, out_dir):
    already_present_count = glob.glob(out_dir + "*.jpg")
    print("No of images already present ", len(already_present_count))
    print(path_list)
    print(out_dir)

    for path in tqdm(path_list):
        out_path = os.path.join(out_dir, os.path.splitext(os.path.basename(path))[0])
        file_exists = glob.glob(out_path + "*.jpg")
        print(file_exists)
        if len(file_exists) != 0:
            print("Files Already exist: ", out_path)
            continue

        for idx, frame in enumerate(frame_extract(path)):
            if idx <= 150:
                # Detect faces using MTCNN
                faces = detector.detect_faces(frame)
                print(faces)

                for i, face in enumerate(faces):
                    bbox = face["box"]
                    print(bbox)
                    top, right, bottom, left = bbox
                    print(top, right, bottom, left)

                    # Extract the face
                    # face_image = frame[top:bottom, left:right, :]
                    face_image = frame[right : right + left, top : top + bottom]
                    print(i)
                    print(frame)
                    print(frame[right : right + left, top : top + bottom])

                    # Save the face as an image
                    face_filename = f"{out_path}_{idx}_face_{i}.jpg"
                    cv2.imwrite(face_filename, face_image)

In [51]:
create_face_images(
    video_files, "F:/Master/Research Project/Generated Data/DFDC_Face_only_data"
)

No of images already present  0
['F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\aassnaulhq.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\abebnhqyzv.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\abxtkdjyru.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\acljesxipy.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\adwbthsgqb.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\aelsfznuqw.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\aeovzefbpr.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\aeudhfvcvk.mp4', 'F:\\Master\\Research Project\\Datasets\\DFDC\\Experiment Dataset\\dfdc_train_part_1_exp\\afqfrfdowg.mp4', 'F:\

  0%|          | 0/1699 [00:00<?, ?it/s]

[]
1/1 [==============================] - 0s 89ms/step
[{'box': [853, 156, 106, 132], 'confidence': 0.8496999144554138, 'keypoints': {'left_eye': (879, 201), 'right_eye': (928, 202), 'nose': (899, 214), 'mouth_left': (881, 252), 'mouth_right': (921, 253)}}]
[853, 156, 106, 132]
853 156 106 132
0
[[[141 146 157]
  [136 141 152]
  [130 135 146]
  ...
  [ 17  24  25]
  [ 17  24  25]
  [ 17  24  25]]

 [[138 143 154]
  [135 140 151]
  [129 134 145]
  ...
  [ 17  24  25]
  [ 17  24  25]
  [ 17  24  25]]

 [[135 140 151]
  [131 136 147]
  [128 133 144]
  ...
  [ 17  24  25]
  [ 17  24  25]
  [ 17  24  25]]

 ...

 [[ 74  63  72]
  [ 75  64  73]
  [ 74  63  72]
  ...
  [ 23  17  20]
  [ 23  17  20]
  [ 23  17  20]]

 [[ 64  51  67]
  [ 65  52  68]
  [ 67  54  70]
  ...
  [ 23  17  20]
  [ 23  17  20]
  [ 23  17  20]]

 [[ 73  60  76]
  [ 74  61  77]
  [ 75  62  78]
  ...
  [ 23  17  20]
  [ 23  17  20]
  [ 23  17  20]]]
[[[64 69 80]
  [64 69 80]
  [64 69 80]
  ...
  [60 65 76]
  [60 65 76]
  

  0%|          | 1/1699 [02:11<61:59:00, 131.41s/it]

[]
1/1 [==============================] - 0s 17ms/step
[{'box': [738, 148, 267, 317], 'confidence': 0.9848814010620117, 'keypoints': {'left_eye': (803, 254), 'right_eye': (935, 258), 'nose': (865, 286), 'mouth_left': (812, 377), 'mouth_right': (918, 381)}}]
[738, 148, 267, 317]
738 148 267 317
0
[[[ 68  80  67]
  [ 67  79  66]
  [ 65  77  64]
  ...
  [125 127 143]
  [124 126 142]
  [123 125 141]]

 [[ 71  83  70]
  [ 68  80  67]
  [ 66  78  65]
  ...
  [128 130 146]
  [126 128 144]
  [126 128 144]]

 [[ 73  85  72]
  [ 72  84  71]
  [ 69  81  68]
  ...
  [133 135 151]
  [132 134 150]
  [132 134 150]]

 ...

 [[ 36  20  89]
  [ 38  22  91]
  [ 38  24  86]
  ...
  [  4   0  10]
  [  4   0  10]
  [  4   0  10]]

 [[ 37  21  90]
  [ 39  23  92]
  [ 38  24  86]
  ...
  [  4   0  10]
  [  4   0  10]
  [  4   0  10]]

 [[ 38  22  91]
  [ 40  24  93]
  [ 39  25  87]
  ...
  [  4   0  10]
  [  4   0  10]
  [  4   0  10]]]
[[[111 111 123]
  [111 111 123]
  [111 111 123]
  ...
  [142 140 145]
  [

  0%|          | 2/1699 [04:32<64:45:12, 137.37s/it]

[]
1/1 [==============================] - 0s 15ms/step
[{'box': [915, 130, 142, 176], 'confidence': 0.9875171780586243, 'keypoints': {'left_eye': (956, 188), 'right_eye': (1019, 195), 'nose': (972, 221), 'mouth_left': (942, 256), 'mouth_right': (996, 264)}}]
[915, 130, 142, 176]
915 130 142 176
0
[[[134 147 155]
  [134 147 155]
  [134 147 155]
  ...
  [ 33  25  33]
  [ 34  26  34]
  [ 34  26  34]]

 [[134 147 155]
  [134 147 155]
  [134 147 155]
  ...
  [ 33  25  33]
  [ 34  26  34]
  [ 34  26  34]]

 [[135 147 157]
  [135 147 157]
  [134 146 156]
  ...
  [ 31  23  31]
  [ 33  25  33]
  [ 31  23  31]]

 ...

 [[ 73  84  78]
  [ 65  76  70]
  [ 61  67  62]
  ...
  [ 24  16  18]
  [ 25  17  19]
  [ 28  20  22]]

 [[ 71  82  76]
  [ 66  77  71]
  [ 66  72  67]
  ...
  [ 29  21  23]
  [ 26  18  20]
  [ 26  18  20]]

 [[ 69  80  74]
  [ 67  78  72]
  [ 70  76  71]
  ...
  [ 31  23  25]
  [ 28  20  22]
  [ 26  18  20]]]
[[[51 58 69]
  [51 58 69]
  [51 58 69]
  ...
  [46 51 62]
  [46 51 62]
 

  0%|          | 3/1699 [06:42<63:03:11, 133.84s/it]

[]
1/1 [==============================] - 0s 15ms/step
[{'box': [962, 309, 133, 156], 'confidence': 0.7639288306236267, 'keypoints': {'left_eye': (1007, 361), 'right_eye': (1060, 363), 'nose': (1029, 377), 'mouth_left': (1004, 420), 'mouth_right': (1047, 422)}}]
[962, 309, 133, 156]
962 309 133 156
0
[[[ 65  50  51]
  [ 64  49  50]
  [ 62  47  48]
  ...
  [126 112 119]
  [146 132 139]
  [147 133 140]]

 [[ 64  49  50]
  [ 64  49  50]
  [ 62  47  48]
  ...
  [124 110 117]
  [142 128 135]
  [142 128 135]]

 [[ 63  48  49]
  [ 63  48  49]
  [ 60  45  46]
  ...
  [121 107 114]
  [138 124 131]
  [140 126 133]]

 ...

 [[ 16   6  13]
  [ 16   6  13]
  [ 15   5  12]
  ...
  [  9   3   6]
  [  9   3   6]
  [  9   3   6]]

 [[ 15   5  12]
  [ 15   5  12]
  [ 15   5  12]
  ...
  [  9   3   6]
  [  9   3   6]
  [  9   3   6]]

 [[ 15   5  12]
  [ 15   5  12]
  [ 14   4  11]
  ...
  [  9   3   6]
  [  9   3   6]
  [  9   3   6]]]
[[[24 30 34]
  [24 30 34]
  [24 30 34]
  ...
  [34 38 40]
  [34 38 4

  0%|          | 3/1699 [08:29<80:04:18, 169.96s/it]
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mtcnn\mtcnn.py:206: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'Min':
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mtcnn\mtcnn.py:206: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'Min':
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mtcnn\mtcnn.py:206: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'Min':
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mtcnn\mtcnn.py:206: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'Min':


KeyboardInterrupt: 

In [4]:
import torch
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import face_recognition
from tqdm.autonotebook import tqdm


# process the frames
def create_face_videos(path_list, out_dir):
    already_present_count = glob.glob(out_dir + "*.mp4")
    print("No of videos already present ", len(already_present_count))
    print(path_list)
    print(out_dir)

    for path in tqdm(path_list):
        out_path = os.path.join(out_dir, path.split("/")[-1])
        file_exists = glob.glob(out_path)
        if len(file_exists) != 0:
            print("File Already exists: ", out_path)
            continue
        frames = []
        flag = 0
        face_all = []
        frames1 = []
        out = cv2.VideoWriter(
            out_path, cv2.VideoWriter_fourcc("M", "J", "P", "G"), 30, (112, 112)
        )

        for idx, frame in enumerate(frame_extract(path)):
            # if(idx % 3 == 0):
            if idx <= 150:
                frames.append(frame)
                if len(frames) == 4:
                    faces = face_recognition.batch_face_locations(frames)
                    for i, face in enumerate(faces):
                        if len(face) != 0:
                            top, right, bottom, left = face[0]
                        try:
                            out.write(
                                cv2.resize(
                                    frames[i][top:bottom, left:right, :], (112, 112)
                                )
                            )
                        except:
                            pass
                    frames = []
        try:
            del top, right, bottom, left
        except:
            pass
        out.release()


create_face_videos(
    video_files, "F:/Master/Research Project/Generated Data/DFDC_Face_only_data"
)